export enum Days {
    MONDAY_MORNING,
    MONDAY_AFTERNOON,
    TUESDAY_MORNING,
    TUESDAY_AFTERNOON,
    WEDNESDAY_MORNING,
    WEDNESDAY_AFTERNOON,
    THURSDAY_MORNING,
    THURSDAY_AFTERNOON,
    FRIDAY_MORNING,
    FRIDAY_AFTERNOON,
}
